pi_deployment/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('predict.urls'))
]

predict/urls.py
from django.urls import path

import predict
from predict import views
from django.conf.urls import handler404
app_name = 'predict'

urlpatterns = [

    path('', views.index, name='index'),

    path('fuel', views.fuel_page, name='fuel_index'),
    path('price', views.price_page, name='price_index'),
    path('sentiments', views.sentiments, name='sa_index'),

    path('fuelpredict', views.predict_fuel, name='fuelpredict'),
    path('pricepredict', views.predict_price, name='pricepredict'),
    path('get_selected_model', views.get_models, name='get_selected_model'),
    path('get_selected_model_2', views.get_models_2, name='get_selected_model_2'),
    path('get_models_fuel', views.get_models_fuel, name='get_models_fuel'),
    path('get_moteurs_fuel', views.get_moteurs_fuel, name='get_moteurs_fuel'),
    path('fill_sentiments_list', views.fill_sentiments_list, name='fill_sentiments_list'),

    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard_2', views.dashboard_2, name='dashboard2'),
    path('detection', views.detection, name='detection'),
    path('detect_car', views.detect_car, name='detect_car')
]

handler404 = 'predict.views.notfoundpage'

templates/base.html
<!doctype html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Fuel prediction</title>
    </head>
    <body>


    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">DB</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/dashboard_2.html
{% extends "base_template.html" %}
{% block main %}
    {% load static %}
    <iframe style="display:flex;justify-content: center;height: 720px;width: 1280px;margin-left:300px;border: solid;border-color: #1da1f2 ;border-radius:3%;border-style: outset"
            title="test - Page 1" width="600" height="373.5"
            src="https://app.powerbi.com/view?r=eyJrIjoiMzVkYzcwZTYtYTUxOC00NzFjLTgyZTQtMjcyZGUwMDhkZmE0IiwidCI6IjE5NGZjM2I2LWFlNjUtNDZhMy04MjQ0LTNkZmQzYzNjZDZmOSJ9&language=en"
            frameborder="0" allowFullScreen="true"></iframe>
{% endblock %}

templates/detection.html
{% extends "base_template.html" %}
{% block main %}
    {% load static %}
    <div class="modal fade" id="exammarqueeModal" tabindex="-1" role="dialog" aria-labelledby="exammarqueeModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="pt-3">Prediction Result:</h5>
                    <div>The chosen car is:
                    </div>
<div id="loader" style="font-weight: bold;margin-top: 2px;font-size: larger">Loading car info...</div>
                    <div id="prediction" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                    <div id="make" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                    <div id="date" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                    <div id="fuel" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                    <div id="power" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                    <div id="engine" style="font-size: larger;font-weight: bold;margin-top: 5px"></div>

                    <button type="button" style="display: flex;justify-content: flex-end;margin-top: 20px"
                            class="btn btn-secondary" data-dismiss="modal">Close
                    </button>

                </div>
            </div>
        </div>
    </div>
    <!--Profile-setting-->
    <section class="user_profile inner_pages">
        <div class="container">
            <div class="user_profile_info gray-bg padding_4x4_40">
                <div class="upload_user_logo" style="height: 200px;">
                    <div class="upload_newlogo">
                        <input name="upload" type="file">
                    </div>
                </div>
                <div class="dealer_info">
                    <h5>Import a car's image </h5>
                    <form action="" id="post-form">
                        {% csrf_token %}
                        <div class="form-group col-md-3 col-sm-6">
                            <button type="submit" value="Submit" class="btn" data-toggle="modal"
                                    data-target="#exammarqueeModal"><i class="fa fa-search"
                                                                       aria-hidden="true"></i>
                                Detect
                            </button>
                        </div>
                    </form>

                </div>
            </div>

        </div>

    </section>
    <!--/Profile-setting-->
    <script>
        console.log("1")
        $(document).on('submit', '#post-form', function (e) {
            e.preventDefault();
            console.log("2")

            $.ajax({
                type: 'POST',
                url: '{% url "predict:detect_car" %}',
                data: {
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {

                    console.log(json.info)
                    console.log(json.info[0])
                    document.getElementById("prediction").innerHTML = "";
                    document.getElementById("loader").innerHTML = "";

                    document.getElementById("prediction").innerHTML = 'PLATE NUMBER: '+json['result']
                    document.getElementById("make").innerHTML = 'MAKE: '+json.info[0]
                    document.getElementById("date").innerHTML = 'CIRCULATION DATE: '+json.info[1]
                    document.getElementById("fuel").innerHTML = 'FUEL TYPE: '+json.info[2]
                    document.getElementById("power").innerHTML = 'HORSEPOWER: '+json.info[3]
                    document.getElementById("engine").innerHTML = 'ENGINE TYPE: '+json.info[4]

                },
                error: function (xhr, errmsg, err) {


                }
            });
        })
    </script>


{% endblock %}

templates/fuel.html
{% extends "base.html" %}

{% block main %}
    <!-- Modal -->
    <div class="modal fade" id="exammarqueeModal" tabindex="-1" role="dialog" aria-labelledby="exammarqueeModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exammarqueeModalLabel">Prediction Results</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h5 class="pt-3">Prediction:</h5>
                    <div id="prediction"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <a class="btn btn-primary" href="/results" role="button">View DB</a>
                </div>
            </div>
        </div>
    </div>

    <div class="container pt-5">
        <div class="row justify-content-md-center">
            <div class="col-md-4">
                <h4>Fuel Consumption Prediction</h4>
                <form action="" id="post-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="voiture">Voiture</label>
                        <input type="text"  class="form-control" id="voiture" marqueaceholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="moteur">Moteur</label>
                        <input type="text"  class="form-control" id="moteur" marqueaceholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="carburant">Carburant</label>
                        <input type="text" class="form-control" id="carburant" marqueaceholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="marque">Marque</label>
                        <input type="text" class="form-control" id="marque" marqueaceholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="cv">Nombre de chevaux</label>
                        <input type="text" class="form-control" id="cv" marqueaceholder="" required>
                    </div>
                    <div class="form-group">
                        <label for="year">Année</label>
                        <input type="text" class="form-control" id="year" marqueaceholder="" required>
                    </div>
                    <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal"
                            data-target="#exammarqueeModal">Submit
                    </button>
                </form>
            </div>
        </div>
    </div>

    <script>
        $(document).on('submit', '#post-form', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "predict:fuelpredict" %}',
                data: {
                    moteur: $('#moteur').val(),
                    carburant: $('#carburant').val(),
                    marque: $('#marque').val(),
                    cv: $('#cv').val(),
                    year: $('#year').val(),
                    voiture: $('#voiture').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.forms["post-form"].reset();
                    document.getElementById("prediction").innerHTML = json['result']
                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>

{% endblock %}

templates/fuel_db.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/fuel_prediction.html
{% extends "base_template.html" %}
{% block main %}
    {% load static %}
    <div class="modal fade" id="exammarqueeModal" tabindex="-1" role="dialog" aria-labelledby="exammarqueeModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="pt-3">Prediction:</h5>
                    <div id="prediction"style="font-size: larger;font-weight: bold;margin-top: 5px"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary"style="display: flex;justify-content: flex-end;margin-top: 20px" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Intro -->
    <section id="intro-3" style="margin-top: 100px;padding-bottom:150px">
        <div class="container">
            <div class="row">
                <div class="col-md-5">

                    <div class="sidebar_widget sidebar_3">


                        <div class="widget_heading">

                            <h5><i class="fa fa-filter" aria-hidden="true"></i>Estimate Fuel Consumption</h5>

                        </div>


                        <div class="sidebar_filter">

                            <form action="" id="post-form">
                                {% csrf_token %}
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="marque">
                                            <option value="">Select Brand</option>
                                            {% for marque in marques %}
                                                <option value="{{ marque }}">{{ marque }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="voiture">
                                            <option value="">Select Model</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="moteur">
                                            <option value="">Select Motor</option>
                                            {% for motor in moteurs %}
                                                <option value="{{ motor }}">{{ motor }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="carburant">
                                            <option>Fuel Type</option>
                                            <option>Essence</option>
                                            <option>Diesel</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="year">
                                            <option>Select Year</option>
                                            <option value="1980">1980</option>
                                            <option value="1981">1981</option>
                                            <option value="1982">1982</option>
                                            <option value="1983">1983</option>
                                            <option value="1984">1984</option>
                                            <option value="1985">1985</option>
                                            <option value="1986">1986</option>
                                            <option value="1987">1987</option>
                                            <option value="1988">1988</option>
                                            <option value="1989">1989</option>
                                            <option value="1990">1990</option>
                                            <option value="1991">1991</option>
                                            <option value="1992">1992</option>
                                            <option value="1993">1993</option>
                                            <option value="1994">1994</option>
                                            <option value="1995">1995</option>
                                            <option value="1996">1996</option>
                                            <option value="1997">1997</option>
                                            <option value="1998">1998</option>
                                            <option value="1999">1999</option>
                                            <option value="2000">2000</option>
                                            <option value="2001">2001</option>
                                            <option value="2002">2002</option>
                                            <option value="2003">2003</option>
                                            <option value="2004">2004</option>
                                            <option value="2005">2005</option>
                                            <option value="2006">2006</option>
                                            <option value="2007">2007</option>
                                            <option value="2008">2008</option>
                                            <option value="2009">2009</option>
                                            <option value="2010">2010</option>
                                            <option value="2011">2011</option>
                                            <option value="2012">2012</option>
                                            <option value="2013">2013</option>
                                            <option value="2014">2014</option>
                                            <option value="2015">2015</option>
                                            <option value="2016">2016</option>
                                            <option value="2017">2017</option>
                                            <option value="2018">2018</option>
                                            <option value="2019">2019</option>
                                            <option value="2020">2020</option>
                                            <option value="2021">2021</option>
                                            <option value="2022">2022</option>
                                        </select>

                                    </div>
                                </div>
                                <div class="form-group col-md-6">
                                    <div class="select">
                                        <select class="form-control" id="cv">
                                            <option>Horsepower</option>
                                            <option>4</option>
                                            <option>5</option>
                                            <option>6</option>
                                            <option>7</option>
                                            <option>8</option>
                                            <option>9</option>
                                            <option>10</option>
                                            <option>11</option>
                                            <option>12</option>
                                            <option>13</option>
                                            <option>14</option>
                                            <option>15</option>
                                            <option>16</option>
                                            <option>17</option>
                                            <option>18</option>
                                            <option>19</option>
                                            <option>20</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <button type="submit" class="btn btn-block" data-toggle="modal"
                                            data-target="#exammarqueeModal"><i class="fa fa-search"
                                                                               aria-hidden="true"></i> Estimate
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>


                </div>
                <div class="col-md-7">
                    <div class="intro-img-wp">
                        <img style="height: 500px;width: auto;margin-top: 10px;margin-left: 30px"
                             src="{% static "images/pump.png" %}" alt="image">
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- /Intro -->
    <script>
        $(document).on('submit', '#post-form', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "predict:fuelpredict" %}',
                data: {
                    moteur: $('#moteur').val(),
                    carburant: $('#carburant').val(),
                    marque: $('#marque').val(),
                    cv: $('#cv').val(),
                    year: $('#year').val(),
                    voiture: $('#voiture').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.forms["post-form"].reset();
                    document.getElementById("prediction").innerHTML = json['result'] + ' liters/100KM'
                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>
    <script>
        $("#marque").change(function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "predict:get_models_fuel" %}',
                data: {
                    marque: $('#marque').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("voiture").innerHTML = "";
                    select = document.getElementById("voiture")
                    for (var i in json) {
                        for (var j in json[i]) {
                            $(select).append('<option value=' + json[i][j] + '>' + json[i][j] + '</option>');
                        }
                    }

                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>
    <script>
        $("#voiture").change(function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "predict:get_moteurs_fuel" %}',
                data: {
                    voiture: $('#voiture').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("moteur").innerHTML = "";
                    select = document.getElementById("moteur")
                    for (var i in json) {
                        for (var j in json[i]) {
                            $(select).append('<option value=' + json[i][j] + '>' + json[i][j] + '</option>');
                        }
                    }

                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>


{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/sentiment_analysis.html
{% extends "base_template.html" %}
{% block main %}
    {% load static %}
    <section class="listing-page">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-md-push-3" id="reviews">
                    <div class="product-listing-m gray-bg" id="review">
                        <div class="product-listing-content">
                            <h5><a href="#">Reviews will be shown here!</a></h5>
                        </div>
                    </div>
                </div>

                <!--Side-Bar-->
                <aside class="col-md-3 col-md-pull-9">
                    <div class="sidebar_widget sidebar_search_wrap">
                        <div class="widget_heading">
                            <h5><i class="fa fa-filter" aria-hidden="true"></i> Find Your Dream Car </h5>
                        </div>
                        <div class="sidebar_filter">
                            <form action="" id="post-form">
                                {% csrf_token %}

                                <div class="form-group select">
                                    <select class="form-control" id="brand">
                                        <option>Select Brand</option>
                                        {% for brand in brands %}
                                            <option value="{{ brand }}">{{ brand }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                                <div class="form-group select">
                                    <select class="form-control" id="model">
                                        <option>Select Model</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn btn-block">
                                        <i class="fa fa-search" aria-hidden="true"></i> Search Car
                                    </button>
                                </div>
                            </form>
                        </div>
                        <div class="sidebar_widget sell_car_quote">
                            <div class="white-text div_zindex text-center">
                                <h3>Find Your Car</h3>
                                <p>Estimate a car's price now!</p>
                                <a href="{% url "predict:index" %}" class="btn">Estimate <span class="angle_arrow"><i
                                        class="fa fa-angle-right" aria-hidden="true"></i></span></a></div>
                            <div class="dark-overlay"></div>
                        </div>
                    </div>
                </aside>
                <!--/Side-Bar-->
            </div>
        </div>
    </section>

    <script>
        $("#brand").change(function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url "predict:get_selected_model" %}',
                data: {
                    brand: $('#brand').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("model").innerHTML = "";
                    select = document.getElementById("model")
                    for (var i in json) {
                        for (var j in json[i]) {
                            $(select).append('<option value=' + json[i][j] + '>' + json[i][j] + '</option>');
                        }
                    }

                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>

    <script>
        $(document).on('submit', '#post-form', function (e) {
            e.preventDefault();
            console.log("1")
            $.ajax({
                type: 'POST',
                url: '{% url "predict:fill_sentiments_list" %}',
                data: {
                    brand: $('#brand').val(),
                    model: $('#model').val(),
                    csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                    action: 'post'
                },
                success: function (json) {
                    document.getElementById("reviews").innerHTML = "";
                    var reviews = document.getElementById("reviews")
                    console.log(json)
                    for (var i of json.reviews) {
                        console.log(i[1])
                        $(reviews).append(''+
                            '<div class="product-listing-m gray-bg" id="review">'+
                            '<div style="margin-left: 20px" class="">'+
                            '<h5><a href="#"></a></h5>'+
                            '<p class="list-price"style=""><strong>'+ i[5] +' ('+ i[10]+')</strong><i></i></p>'+
                            '<p class="">'+ i[9] +'<i></i></p>'+
                            '<ul>'+
                                '<li><i class="fa fa-star" aria-hidden="true"></i>'+ i[3] +'</li>'+
                                '<li><i class="fa fa-calendar" aria-hidden="true"></i>'+ i[6] +'</li>'+
                                '<li><i class="fa fa-car" aria-hidden="true"></i>'+ i[4] +'</li>'+
                                '<li><i class="fa fa-user" aria-hidden="true"></i>'+ i[7] +'</li>'+
                            '</ul>'+
                            '<div class="fa fa-location-arrow"><span> '+ i[8] +'</span>'+
                            '</div>'+
                        '</div>'+
                    '</div>'+
                        '');
                    }

                },
                error: function (xhr, errmsg, err) {

                }
            });
        })
    </script>
{% endblock %}